10 REM KAHLESS THE FINAL REFLECTION VOCAB PROGRAM
20 dim DICT$(200)
30 for i = 1 to 147
100 READ T$ 
150 DICT$(i)=T$
200 PRINT i
205 print T$
300 next i
1000 for i = 1 to 30
1001 print
1002 next i
1010 print "What would you like to search for from Kahless or The Final Reflection?"
1015 input sr$
1020 for s = 1 to 147
1025 if instr(DICT$(s),sr$)>0 then 1030 else 1040
1030 print DICT$(s)
1040 next s
1041 for  i=1 to  3
1042 print
1043 next i
1050 goto 1010
2000 DATA "Adjur a modern Klingon  KAHLESS" 
2010 DATA "Anag an ancient Klingon KAHLESS" 
2020 DATA "B'aaj an island or continent on Qo'noS, or a planet KAHLESS" 
2030 DATA "Badich an ancient Klingon (a healer) KAHLESS" 
2040 DATA "Bogra an ancient Klingon  KAHLESS" 
2050 DATA "Boreth a monastery  KAHLESS" 
2060 DATA "Chu'paq Sea  KAHLESS" 
2070 DATA "DIS jajlo'0a cave, stated to mean ''dawn cave'' KAHLESS" 
2080 DATA "Divok a modern Klingon  KAHLESS" 
2090 DATA "Donar'ruq a city on Ter'jas Mor  KAHLESS" 
2100 DATA "DujIIj yIvog ''trust your instincts''  KAHLESS" 
2110 DATA "Duras a modern Klingon  KAHLESS" 
2120 DATA "Edronh an ancient Klingon  KAHLESS" 
2130 DATA "Fek'lhr guardian of Gre'thor KAHLESS" 
2140 DATA "Godar a modern Klingon  KAHLESS" 
2150 DATA "Gon'rai Rebellion   (modern times, may not be on Qo'noS)" 
2160 DATA "Gowron a modern Klingon  KAHLESS" 
2170 DATA "Gre'thor hell KAHLESS" 
2180 DATA "Inagh a modern Klingon  (father of Rajuc) KAHLESS" 
2190 DATA "Kanjis1an ancient Klingon  (father of Kahless) KAHLESS" 
2200 DATA "Kardem a modern Klingon  KAHLESS" 
2210 DATA "Kellein an ancient Klingon (Vathraq's daughter)  KAHLESS" 
2220 DATA "Kerpach(a modern Klingon  (shopkeeper) KAHLESS" 
2230 DATA "Kerret'raa an island or continent on Qo'noS, or a planet" 
2240 DATA "Koroth a modern Klingon  KAHLESS" 
2250 DATA "Kri'stak a volcano  KAHLESS" 
2260 DATA "Kurn.a modern Klingon  (brother of Worf) KAHLESS" 
2270 DATA "Lomakh a modern Klingon  KAHLESS" 
2280 DATA "Lusor a lake KAHLESS" 
2290 DATA "M'rel a modern Klingon  KAHLESS" 
2300 DATA "M'riiah a village  KAHLESS" 
2310 DATA "Majjas a modern Klingon  KAHLESS" 
2320 DATA "Mogh-a modern Klingon (father of Worf) 130 KAHLESS" 
2330 DATA "Molor an ancient Klingon: the tyrant  KAHLESS" 
2340 DATA "Morath an ancient Klingon  (brother of Kahless) KAHLESS" 
2350 DATA "Muar'tek Festival  KAHLESS" 
2360 DATA "Muuda a modern Klingon  KAHLESS" 
2370 DATA "Najuk a modern Klingon  KAHLESS" 
2380 DATA "Navrath a city near Tolar'tu  KAHLESS" 
2390 DATA "Noj a modern Klingon  KAHLESS" 
2400 DATA "Ogat a Klingon colony world  KAHLESS" 
2410 DATA "Olahg a modern Klingon  KAHLESS" 
2420 DATA "Ona'ja'bur some natural steam baths in a cavern 158 KAHLESS" 
2430 DATA "Ondagh an ancient Klingon  KAHLESS" 
2440 DATA "Porus an ancient Klingon  KAHLESS" 
2450 DATA "Praxis the moon of Qo'noS  KAHLESS" 
2460 DATA "Qa'yarin.a place where Molor's fortress was  KAHLESS" 
2470 DATA "Ra'jahn a place on Kerret'raa  KAHLESS" 
2480 DATA "Rajuc a modern Klingon  (a schoolmaster) KAHLESS" 
2490 DATA "Rannuf an ancient Klingon KAHLESS" 
2500 DATA "Restagh a modern Klingon KAHLESS" 
2510 DATA "Shurin an ancient Klingon  KAHLESS" 
2520 DATA "Starad,an ancient Klingon  (son of Molor) KAHLESS" 
2530 DATA "Sto-Vo-Kor Valhalla KAHLESS" 
2540 DATA "T'chariv a village  KAHLESS" 
2550 DATA "Ter'jas Mor an island or continent on Qo'noS, or a planet KAHLESS" 
2560 DATA "Tichar a modern Klingon  KAHLESS" 
2570 DATA "Tolar'tu a town  KAHLESS" 
2580 DATA "Toragh an ancient Klingon  (a smith) KAHLESS" 
2590 DATA "Uhq'ra Mountains  KAHLESS" 
2600 DATA "Unagroth a modern Klingon  KAHLESS" 
2610 DATA "Unarrh a modern Klingon  KAHLESS" 
2620 DATA "Vathraq an ancient Klingon (a lord, friendly to Kahless) " 
2630 DATA "Yap  (stated to mean ''Enough'') ( Okrand (yap)) KAHLESS" 
2640 DATA "Yatron an ancient Klingon  (son of Molor) KAHLESS" 
2650 DATA "abin'do a sort of pipe (musical instrument)  KAHLESS" 
2660 DATA "bIjeghbe'chugh vaj bIHegh! ''surrender or die!''  KAHLESS " 
2670 DATA "caw'va a species of fruit like a melon  KAHLESS" 
2680 DATA "cob'lat a big predatory animal?  KAHLESS" 
2690 DATA "d'k tahg a sort of 3-bladed dagger KAHLESS" 
2700 DATA "darsekmey (pl.) (probably) a sort of coin  KAHLESS" 
2710 DATA "en'chula a species of red grass  KAHLESS" 
2720 DATA "gagh a species of worm (= Okrand (qagh)) KAHLESS" 
2730 DATA "jinaq a sort of amulet  KAHLESS" 
2740 DATA "ko'tal (noun, some sort of person) (meaning unclear) KAHLESS" 
2750 DATA "krad'dak.a sort of drum (musical instrument)  KAHLESS" 
2760 DATA "kraw'za1a species of black carrion-eating bird  KAHLESS" 
2770 DATA "m'ressa a sort of wood (= timber) KAHLESS" 
2780 DATA "micayah a species of tree  KAHLESS" 
2790 DATA "minn'hor a domestic & wild animal like an ox  KAHLESS" 
2800 DATA "mok'bara a sort of clothes  KAHLESS" 
2810 DATA "mok'bara a sort of fighting technique  KAHLESS" 
2820 DATA "p'tahk an insult of contempt KAHLESS (pl. p'tahkmey )" 
2830 DATA "pherza a species of stinging wasp  (makes wax ) KAHLESS" 
2840 DATA "qava a sort of wood (= timber) KAHLESS" 
2850 DATA "rach'tor hunter?  KAHLESS" 
2860 DATA "s'tarahk a species of riding animal (pl. s'tarahkmey ) KAHLESS" 
2870 DATA "skannu a sort of big black tree  KAHLESS" 
2880 DATA "targ a species of animal  (Okrand (targh)) KAHLESS" 
2890 DATA "teqal'ya a sort of wood (= timber)  KAHLESS" 
2900 DATA "thranx a species of bush, flowers every 8th year  KAHLESS" 
2910 DATA "tor'rif a sort of bread  KAHLESS" 
2920 DATA "tran'nuca sort of tree fruit  KAHLESS" 
2930 DATA "warnog a sort of drink  KAHLESS" 
2940 DATA "yolok a species of worm  KAHLESS" 
3000 DATA "federazhon          The United Federation of Planets. [TFR]"
3010 DATA "fedegonaase       UFP standard language, whatever that is. [TFR]"
3020 DATA "gagny               Damned. [TFR]"
3030 DATA "g'dayt              Undefined adjectives (gerunds?), roughly equivalent [TFR]"
3040 DATA "g'daya              to ''damned,'' but probably stronger. [TFR]"
3050 DATA "kaase               Hand. [TFR]"
3060 DATA "Kahlesste kaase!  ''Kahless' hand,'' an oath referring to a story of  Kahless [TF"
3070 DATA "kai                 Hail, or ''long live''.  Used often, as ''Kai ''. [TFR]"
3080 DATA "kai kassai        The same, emphasized.  ''Kai kassai, Klingon!'' [TFR]"
3090 DATA "khesterex           Literally, ''the structure which dies.'' [TFR]"
3100 DATA "khest             To screw up. [TFR]"
3110 DATA "khesterex thath   Screwed up situation. [TFR]"
3120 DATA "kherx             A screw-up. [TFR]"
3130 DATA "parkhest          Damn! [TFR]"
3140 DATA "khest'n           Apparently interchangable adjectives, roughly equal [TFR]"
3150 DATA "khest't           to ''damned.'' [TFR]"
3160 DATA "kleon               Enemy, or opponent.  Same, to a Klingon. [TFR]"
3170 DATA "klin                That which is Klingon.  One can be 'full of klin' [TFR]"
3180 DATA "Klingon           Klingon.  Noun only, I think. [TFR]"
3190 DATA "Klinzhai          The Klingon homeworld -- not called 'Klingon'! [TFR]"
3200 DATA "klingonaase       The Klingonese language. [TFR]"
3210 DATA "komerex             Literally, ''the structure which grows.'' [TFR]"
3220 DATA "komerex Klingon   The Klingon Empire. [TFR]"
3230 DATA "komerex zha       See 'zha' below. [TFR]"
3240 DATA "kuve                Servitor; alternative translation is slave. [TFR]"
3250 DATA "kuvekhestat       Worthless slave(s).  See 'khest' above. [TFR]"
3260 DATA "kuveleta          Half-slave; an insult.  Klingons mix races freely [TFR]"
3270 DATA "kuvesa tokhesa    ''I serve willingly.'' [TFR]"
3280 DATA "tharkuve          Deaf slave, unable to overhear secret conferences. [TFR]"
3290 DATA "haravul          Vulcan servitor [TFR]"
3300 DATA "nal          Negating word -- as, ''Nal komerex, khesterex.'' [TFR]"
3310 DATA "straave, straav'    Slave. [TFR]"
3320 DATA "tokhe straav'     Willing slave.  Just about the worst insult one can call a Klingon. [TFR]"
3330 DATA "tai                 Worthy, honored. [TFR]"
3340 DATA "  epetai-zana       Honored and exalted one. [TFR]"
3350 DATA "  tai-kleon         Worthy opponent.  See 'kleon' above. [TFR]"
3360 DATA "teskas              Compliments, praise. [TFR]"
3370 DATA "teskas tal'tai-kleon  Compliments to a worthy opponent. [TFR]"
3380 DATA "tokhe               Willing.  See 'straave' and 'kuve' above. [TFR]"
3390 DATA "vird'dakaase        Disruptor.  Literally, ''shake-till-falls-apart tool.'' [TFR]"
3400 DATA "zan		    Neutral title of respect; roughly equal to Mister. [TFR]"
3410 DATA "zha                 Game. [TFR]"
3420 DATA "klin zha          The Klingon game (in several variations). [TFR]"
3430 DATA "klin zha kinta  The Klingon game with living pieces. [TFR]"
3440 DATA "hum zha           The Human game, chess. [TFR]"
3450 DATA "rom zha           The Romulan game, latrunculo. [TFR]"
3460 DATA "komerex zha       The perpetual game -- life.  See 'komerex' above. [TFR]"
3470 DATA "zha riest'n       [It was a] pleasant game. [TFR]"
3480 DATA "sa tel'ren          Two out of three.  One can't assume sa=2 and ren=3. [TFR]"
3490 DATA "humanai kuvest'     Either ''human slave'' or ''slave of the humans.'' [TFR]"
3500 DATA "tokhest'            From context, ''if he is willing or not.'' [TFR]"
3510 DATA "komerex tel khesterex  This was an interjection, probably ''grow or die.'' [TFR]"
